src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column]
    private ?int $car_km = null;

    #[ORM\Column(length: 255)]
    private ?string $energy = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'car', targetEntity: CarImage::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $carImages;

    public function __construct()
    {
        $this->carImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getCarKm(): ?int
    {
        return $this->car_km;
    }

    public function setCarKm(int $car_km): static
    {
        $this->car_km = $car_km;

        return $this;
    }

    public function getEnergy(): ?string
    {
        return $this->energy;
    }

    public function setEnergy(string $energy): static
    {
        $this->energy = $energy;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, CarImage>
     */
    public function getCarImages(): Collection
    {
        return $this->carImages;
    }

    public function addCarImage(CarImage $carImage): static
    {
        if (!$this->carImages->contains($carImage)) {
            $this->carImages->add($carImage);
            $carImage->setCar($this);
        }

        return $this;
    }

    public function removeCarImage(CarImage $carImage): static
    {
        if ($this->carImages->removeElement($carImage)) {
            // set the owning side to null (unless already changed)
            if ($carImage->getCar() === $this) {
                $carImage->setCar(null);
            }
        }

        return $this;
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Car;
use App\Form\SearchType;
use App\Repository\CarImageRepository;
use App\Repository\CarRepository;
use App\Repository\SchedulesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CarController extends AbstractController
{
    #[Route('/car', name: 'app_car')]
    public function index(CarRepository $carRepository, CarImageRepository $carImageRepository, SchedulesRepository $schedulesRepository, Request $request): Response
    {
        $data = new SearchData();
        $form = $this->createForm(SearchType::class, $data);
        $form->handleRequest($request);
        $cars = $carRepository->findSearch($data);
        return $this->render('car/index.html.twig', [
            'cars' => $cars,
            'images' => $carImageRepository->findAll(),
            'schedules' => $schedulesRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }
}

templates/car/car-list.html.twig
{% for car in cars %}
{% include 'car/car.html.twig'%}
{% endfor %}

templates/car/car.html.twig
<div class="card">
    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% for carImage in car.carImages %}
            <div class="carousel-item {% if loop.first %}active{% endif %}">
                <img src="{{ asset('uploads/' ~ carImage.name) }}" class="d-block w-100" alt="...">
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="card-body">
        <h5 class="card-title">{{ car.brand }} {{ car.model }}</h5>
        <p class="card-text">{{ car.price|number_format (0, ',', ' ') }} €<br>
            {{ car.carKm|number_format (0, ',', ' ') }} KM<br>
            {{ car.energy }}
        </p>
        <div class=" btns text-center">
            <a href="{{path('app_contact_form')}}" class="btn" id="carContactBtn"><svg
                    xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-envelope-open"
                    viewBox="0 0 16 16">
                    <path
                        d="M8.47 1.318a1 1 0 0 0-.94 0l-6 3.2A1 1 0 0 0 1 5.4v.817l5.75 3.45L8 8.917l1.25.75L15 6.217V5.4a1 1 0 0 0-.53-.882l-6-3.2ZM15 7.383l-4.778 2.867L15 13.117V7.383Zm-.035 6.88L8 10.082l-6.965 4.18A1 1 0 0 0 2 15h12a1 1 0 0 0 .965-.738ZM1 13.116l4.778-2.867L1 7.383v5.734ZM7.059.435a2 2 0 0 1 1.882 0l6 3.2A2 2 0 0 1 16 5.4V14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5.4a2 2 0 0 1 1.059-1.765l6-3.2Z" />
                </svg></a>

            <!-- Button trigger modal -->
            <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal{{car.id}}">
                En savoir plus
            </button>

        </div>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal{{car.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">{{ car.brand }} {{ car.model }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
                    </div>
                    <div class="modal-body">
                        <h3>Infos</h3>
                        <p>
                            Prix : {{ car.price|number_format (0, ',', ' ') }}€<br>
                            Année : {{ car.year|number_format (0, ',', ' ') }} <br>
                            Carburant : {{ car.energy }}<br>
                            Kilométrage : {{ car.CarKm|number_format (0, ',', ' ') }} KM

                        </p>
                        <h3>Description</h3>
                        <p>{{ car.description|raw }}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}

<div class="container">
    <div class="filter mt-3">

        {{ form_start(form, {'attr': {'id': 'searchForm'}}) }}
        {{ form_row(form.q)}}

        <h4>Prix</h4>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.minPrice, {'attr': {'id': 'minPrice'}})}}
            </div>
            <div class="col-md-6">
                {{ form_row(form.maxPrice, {'attr': {'id': 'maxPrice'}})}}
            </div>

        </div>


        <h4>Année</h4>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.minYear, {'attr': {'id': 'minYear'}})}}
            </div>
            <div class="col-md-6">
                {{ form_row(form.maxYear, {'attr': {'id': 'maxYear'}})}}
            </div>
        </div>

        <h4>Kilométrage</h4>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.minKm, {'attr': {'id': 'minKm'}})}}
            </div>
            <div class="col-md-6">
                {{ form_row(form.maxKm, {'attr': {'id': 'maxKm'}})}}
            </div>
        </div>

        <button type="submit" class="btn" id="filterBtn">Filtrer</button>

        {{ form_end(form) }}



        <div class="container">
            <h1 class="my-4"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                    class="bi bi-car-front-fill" viewBox="0 0 16 16">
                    <path
                        d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679c.033.161.049.325.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.807.807 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2H6ZM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17 1.247 0 3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z" />
                </svg> Annonces</h1>
            <div class="d-flex flex-wrap gap-3 justify-content-center" id="carsContainer">
                {% include 'car/car-list.html.twig' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}